import mysql.connector
db=mysql.connector.connect(user='root',password='Mathan@123',host='localhost',database='colleage')
var=db.cursor()
#var.execute("create database colleage")
#print("database completed")
#var.execute("use database colleage")
#print("used database")
#var.execute("create table student(id int,name varchar(20),age int,mark int)")
#print("table created")
#db.commit()
#var.execute("insert into student values(1,'arun',24,98)")
#db.commit()
#var.execute("insert into student values(2,'kumar',25,88)")
#var.execute("insert into student values(3,'raj',31,72)")
#var.execute("insert into student values(4,'dinesh',22,98)")
#var.execute("insert into student values(5,'nava',24,98)")
#db.commit()
#var.execute("update student set name='raj kumar' where id=3")
#db.commit()
#print("updated")
#var.execute("delete from student where id=3")
#db.commit()
#print("deleted")
#var.execute("alter table student add column mark1 int")
var.execute("alter table student drop mark1")